WebApplication1/Models/Phone.cs
namespace WebApplication1.Models;

public class Phone
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Price { get; set; }
    public string Company { get; set; }
    public int CameraCount { get; set; }
}

WebApplication1/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers;

public class OrderController : Controller
{
    private readonly PhoneStoreContext _context;

    public OrderController(PhoneStoreContext context)
    {
        _context = context;
    }
    // GET
    public IActionResult Index()
    {
        List<Order> orders = _context.Orders.Include(o => o.Phone).ToList();
        List<Phone> phones = _context.Phones.ToList();

        PhonesOrdersViewModel vm = new PhonesOrdersViewModel()
        {
            Phones = phones,
            Orders = orders
        };
        return View(vm);
    }

    //Edit
    public IActionResult Edit(int id)
    {
        Order o = _context.Orders.FirstOrDefault(x => x.Id == id);
        return View(o);
    }

    [HttpPost]
    public IActionResult Edit(Order order)
    {
        _context.Update(order);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Create(int id)
    {
        Phone p = _context.Phones.FirstOrDefault(x => x.Id == id);
        ViewBag.Phone = p;
        return View();
    }

    [HttpPost]
    public IActionResult Create(Order order)
    {
        if (order != null)
        {
            Order o = new Order()
            {
                Name = order.Name,
                Address = order.Address,
                ContactPhone = order.ContactPhone,
                PhoneId = order.PhoneId
            };
            
            _context.Add(o);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return NotFound();
    }
    
}

WebApplication1/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers;

public class PhoneController : Controller
{
    private readonly PhoneStoreContext _context;
    private readonly IWebHostEnvironment _environment;

    public PhoneController(PhoneStoreContext context, IWebHostEnvironment environment)
    {
        _context = context;
        _environment = environment;
    }

    public IActionResult GetMessage()
    {
        return PartialView("_GetMessage");
    }
    public IActionResult Index()
    {
        List<Phone> phones = _context.Phones.ToList();
        return View(phones);
    }

    public IActionResult Create()
    {
        return View();
    }

    public IActionResult GetFile(string phoneName)
    {
        string filename = $"{phoneName}.txt";
        string path = Path.Combine(_environment.WebRootPath, "file", filename);
        string fileType = "text/txt";
        
        if (System.IO.File.Exists(path))
        {
            return PhysicalFile(path, fileType, filename);
        }
        else
        {
            return NotFound($"{phoneName} такой файл не найдено!");
        }
    }
    
    //task2
    public IActionResult Test(string company)
    {
        Phone phones = _context.Phones.FirstOrDefault(x => x.Company == company);
        if (phones.Company == "Apple")
            return RedirectPermanent("https://www.apple.com/");
        else if (phones.Company == "Samsung")
            return RedirectPermanent("https://www.samsung.com/ru/");
        else if (phones.Company == "MI")
            return RedirectPermanent("https://www.mi.com/ru/");
        else
            return NotFound();
    }
    
    //task3
    public IActionResult Edit(int id)
    {
        Phone p = _context.Phones.FirstOrDefault(x => x.Id == id);
        if (p == null)
        {
            return NotFound($"Phone with this id: {id} not found");
        }
        else
        {
            return View(p);
        }
    }

    [HttpPost]
    public IActionResult Edit(Phone phone)
    {
        try
        {
            if (phone != null)
            {
                _context.Update(phone);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
        return View(phone);
    }
    //-------------------------------------------
    
    [HttpPost]
    public IActionResult Create(Phone phone)
    {
        if (phone != null)
        {
            _context.Add(phone);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(phone);
    }
    //-------------------------------------------
    //Details
    [HttpGet]
    public IActionResult Details(int id)
    {
        List<Phone> phones = _context.Phones.ToList();
        var findId = phones.FirstOrDefault(p => p.Id == id);
        return View(findId);
    }

    public async Task<IActionResult> Details2(int id)
    {
        Phone? phone = await _context.Phones.FirstOrDefaultAsync(p => p.Id == id);
        if (phone != null)
        {
            return View(phone);
        }

        return NotFound();
    }
    //-------------------------------------------
    //Delete

    public async Task<IActionResult> Delete(int id)
    {
        Phone? phone = await _context.Phones.FirstOrDefaultAsync(p => p.Id == id);
        if (phone != null)
        {
            _context.Remove(phone);
            await _context.SaveChangesAsync();
        }

        return RedirectToAction("Index");
    }
    //------------------------------------------
    //Edit2

    public async Task<IActionResult> Edit2(int id)
    {
        Phone? phone = await _context.Phones.FirstOrDefaultAsync(p => p.Id == id);
        if (phone != null)
        {
            return View(phone);
        }

        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Edit2(Phone? phone)
    {
        if (phone != null)
        {
            _context.Update(phone);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        return View(phone);
    }
}

WebApplication1/Views/Phone/Create.cshtml
@model Phone

@{
    ViewBag.Title = "Add new Phone";
}
<h2>Заполните форму для добавления устройства</h2>
<div class="row">
    <div class="phone_add_form col-md-6">
        <form asp-action="Create" method="post">
            <div class="form_row">
                <label for="">
                    Наименование
                    <input asp-for="Name" type="text">
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Компания
                    <input asp-for="Company" type="text">
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Стоимость
                    <input asp-for="Price" type="text">
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Количество камера
                    <input asp-for="CameraCount" type="number">
                </label>
            </div>
            <button type="submit">Создать</button>
        </form>
    </div>
</div>

WebApplication1/Views/Phone/Details.cshtml
@model Phone
@{
    ViewBag.Title = "Details";
}

<div class="col-9">
    <h2>Show Phone</h2>
    @if (Model != null)
    {
        <div class="container">
                <ul class="list-group">
                    <li class="list-group-item"><strong>ID: </strong>@Model.Id</li>
                    <li class="list-group-item"><strong>Name: </strong>@Model.Name</li>
                    <li class="list-group-item"><strong>Surname: </strong>@Model.Price</li>
                    <li class="list-group-item"><strong>About: </strong>@Model.Company</li>
                    <li class="list-group-item"><strong>Age: </strong>@Model.CameraCount</li>
                </ul>
        </div>
    }
    else
    {
        <h3>Phone not found</h3>
    }
</div>
<div class="pt-5">
    <a asp-action="GetFile" asp-controller="Phone" asp-route-phoneName="@Model.Name">Download</a>
</div>

WebApplication1/Views/Phone/Details2.cshtml
@model Phone

@{
    ViewData["Title"] = $"{Model.Name}";
}

<div class="container">
    <p>@Model.Name</p>
    <p>@Model.Company</p>
    <p>@Model.Price</p>
    <p>@Model.CameraCount</p>
</div>

WebApplication1/Views/Phone/Edit.cshtml
@model Phone

@{
    ViewBag.Title = "Edit phone";
}

<h2>Edit phone</h2>
<div class="row">
    <div class="phone_add_form col-md-6">
        <form asp-action="Edit" asp-controller="Phone" method="post">
            <div class="form_row">
                <label for="">
                    Название
                    <input asp-for="Name" type="text">
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Компания
                    <input asp-for="Company" type="text">
                </label>
            </div>
            <div class="form_row">
                <label for="">
                    Стоимость
                    <input asp-for="Price" type="text">
                </label>
            </div>
            <div class="form-row">
                <label for="">
                    <input disabled type="hidden" value="@Model.CameraCount">
                </label>
                <input asp-for="CameraCount" type="hidden" value="@Model.Id">
            </div>
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
</div>

WebApplication1/Views/Phone/Index.cshtml
@model List<Phone>

@{
    ViewBag.Title = "All Phones";
}

<h2>All Phones</h2>
<p><a asp-action="Create">Add new Phone</a></p>
@if (Model != null && Model.Count != 0)
{
    <table class="table table-success">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Company</th>
            <th scope="col">Price</th>
            <th scope="col">Camera Count</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <th scope="row"><a asp-action="Details2" asp-route-id="@p.Id">@p.Name</a>
                <td>@p.Company</td>
                <td>@p.Price</td>
                <td>@p.CameraCount</td>
                <td><a asp-action="Details" asp-route-id="@p.Id"><button class="btn btn-outline-success">Details</button></a></td>
                <td><a asp-action="Create" asp-controller="Order" asp-route-id="@p.Id"><button class="btn btn-secondary">Make Order</button></a></td>
                <td><a asp-action="Edit" asp-controller="Phone" asp-route-id="@p.Id"><button class="btn btn-warning">Edit</button></a></td>
                <td><a asp-action="Test" asp-controller="Phone" asp-route-company="@p.Company"><button class="btn btn-primary">Redirects</button></a></td>
                <td><a asp-action="Delete" asp-route-id="@p.Id"><button class="btn btn-danger">Delete</button></a></td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <h3>Нету телефона пока!</h3>
}

@{
    await Html.RenderPartialAsync("_GetMessage", new List<string>(){"1","2","3"});
}

WebApplication1/Views/Phone/_GetMessage.cshtml
@model List<string>

<h4>Hello World</h4>
@foreach (string s in Model)
{
    <p>@s</p>
}